// TypesFromSerializers CacheKey 716e8f92c875dd18d3da550a4d4bb66c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface College {
  id: number;
  createdAt: string | Date;
  name?: string;
  updatedAt: string | Date;
  website?: string;
}
