// TypesFromSerializers CacheKey a7ee10987af820bc42f6b57f7b7ddb4f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export type { default as College } from './College';
export type { default as Organization } from './Organization';
export type { default as User } from './User';
