// TypesFromSerializers CacheKey db849914bf9cbbd3b1c6d9a9a8bf76ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export type { default as College } from './College';
export type { default as Organization } from './Organization';
export type { default as Program } from './Program';
export type { default as User } from './User';
