// TypesFromSerializers CacheKey 1b809ec82d77868bb737c8fa1b05b250
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from './User';

export default interface Invitation {
  id: number;
  acceptedAt?: string | Date;
  acceptedBy: User;
  createdAt: string | Date;
  email: string;
  expiresAt: string | Date;
  inviteCode: string;
  updatedAt: string | Date;
}
// TypesFromSerializers CacheKey 1b809ec82d77868bb737c8fa1b05b250
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from './User';

export default interface Invitation {
  id: number;
  acceptedAt?: string | Date;
  acceptedBy: User;
  createdAt: string | Date;
  email: string;
  expiresAt: string | Date;
  inviteCode: string;
  updatedAt: string | Date;
}
