// TypesFromSerializers CacheKey 1c936ef3203d37be8ab56d4adee6da13
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Organization {
  id: number;
  createdAt: string | Date;
  description?: string;
  domain?: string;
  name?: string;
  updatedAt: string | Date;
}
