// TypesFromSerializers CacheKey 0e12146c14d5a2663bcb3991cb0df83f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Invitation from './Invitation';
import type Organization from './Organization';
import type User from './User';

export default interface OrganizationMembership {
  id: number;
  createdAt: string | Date;
  invitation?: Invitation;
  joinedAt: string | Date;
  organization: Organization;
  updatedAt: string | Date;
  user: User;
}
// TypesFromSerializers CacheKey 0e12146c14d5a2663bcb3991cb0df83f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Invitation from './Invitation';
import type Organization from './Organization';
import type User from './User';

export default interface OrganizationMembership {
  id: number;
  createdAt: string | Date;
  invitation?: Invitation;
  joinedAt: string | Date;
  organization: Organization;
  updatedAt: string | Date;
  user: User;
}
