// TypesFromSerializers CacheKey 2e1cffbb7dec4b883f028bc0017bbf0b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type College from './College';

export default interface Organization {
  id: number;
  colleges: College[];
  createdAt: string | Date;
  description?: string;
  domain?: string;
  name?: string;
  updatedAt: string | Date;
}
