// TypesFromSerializers CacheKey e234864c498c534f0002741698b48f78
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Organization from './Organization';

export default interface Program {
  id: number;
  createdAt: string | Date;
  description?: string;
  name?: string;
  organization: Organization;
  organizationId: number;
  updatedAt: string | Date;
}
