// TypesFromSerializers CacheKey 53eff32aef28d435a4334100ff1ffcdd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  createdAt: string | Date;
  email: string;
  updatedAt: string | Date;
  verified: boolean;
}
