// TypesFromSerializers CacheKey db5a71478d69f2cde0c09132071d3567
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  createdAt: string | Date;
  email: string;
  updatedAt: string | Date;
}
