// TypesFromSerializers CacheKey c7584d832cac802ebbe1c41f52f35c17
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  email: string;
}
